tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install Django
      python manage.py migrate
  - command: |
      source venv/bin/activate
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    addCheck: true
    pullRequestsFromForks: true
